### ISSUE TITLE
Include selfshopping?

### ISSUE THREAD

**Issue by jobhh** [datalogic/datalogic-android-sdk#1]
Is it possible to include _com.datalogic.extension.selfshopping_ in this? That's the thing that we're missing compared to the _compileSdkVersion 'Datalogic:Datalogic SDK v1:xx'_ method :)

**Comment by codybrookshear** [comment]
I actually created a separate (also still experimental) repository for the self-shopping extension:
https://github.com/datalogic/datalogic-android-sdk-selfshopping

**Comment by jobhh** [comment]
Thanks! I missed that repo :)
May I ask why this method is experimental? Are there functions we can expect to be non-functional? The classes seems to be similar on first glance.

Edit:
I encountered my first issue with the experimental selfshopping 👍 
 https://github.com/datalogic/datalogic-android-sdk-selfshopping/issues/1

**Comment by codybrookshear** [comment]
This method is still considered experimental because it's a new approach for us and not tested in any formal way outside the tests performed against the `compileSdkVersion` method.  Thanks for your feedback and letting us know you are using this new "experimental method 👍
