### ISSUE TITLE
Usage with Kotlin?

### ISSUE THREAD

**Issue by eokorieFA** [datalogic/datalogic-android-sdk#2]
Is it possible to use this with Kotlin by any chance?

**Comment by jobhh** [comment]
It should work. Kotlin has no problems using Java libraries.

**Comment by codybrookshear** [comment]
@jobhh is right. we use it internally with Kotlin. We should be posting some sample apps written in Kotlin this summer. I'll reply here once they are posted.

**Comment by eokorieFA** [comment]
That would be awesome.  As I am trying to find a way of using the sdk within a flutter application.  To do that I am using the platform channel to attempt to communicate with the sdk itself.  But since I need to create the code in a Kotlin file, I cannot quite seem to get it to work.  So any code samples you may have on using this library with Kotlin would be greatly appreciated.

**Comment by ahmetkocadogan** [comment]
@codybrookshear  Is there any plan to make a plugin to work with Flutter?

**Comment by codybrookshear** [comment]
@ahmetkocadogan no plans for Flutter support so far. It would be possible to expose a few of the APIs to Flutter on your own if desired.

https://flutter.dev/docs/development/platform-integration/platform-channels

**Comment by eokorieFA** [comment]
@codybrookshear I will be looking forward to the examples on using this package with Kotlin.  It is a bit of a shame that there won't be any examples on using it with Flutter. But this will be a good learning curve.  Just need to figure out how to that into the apis themselves :)

**Comment by ahmetkocadogan** [comment]
@codybrookshear you are right for flutter platform channels/ plugin development. but, why i choose flutter is, to avoid learning java and native code, to be able to write one code for cross platform development. 

I tried to develop a plugin, but i couldn't manage it so far. 

If it's easy for datalogic team to develop, please make a flutter plugin. Thanks.

**Comment by codybrookshear** [comment]
@ahmetkocadogan if there's enough demand for a flutter sdk in the future, we would definitely consider it. we maintain Android (Java/Kotlin), Xamarin and Cordova (for Ionic and Phonegap development) SDKs currently. If you did write your app in flutter, you could still use "keyboard wedge" mode with the scanner if desired.

@eokorieFA our Kotlin samples are now available:

* [Kotlin sample projects](http://www.datalogic.dev/android/samples)
* [Kotlin code snippents in FAQ](http://www.datalogic.dev/android/faq)

**Comment by ahmetkocadogan** [comment]
@codybrookshear i finished my app with Xamarin. Thank you for answers and explanations.

**Comment by eokorieFA** [comment]
@codybrookshear Thank you for supplying the examples. 👍
